import '../models/product_model.dart';
import '../models/order_model.dart';
import '../models/category_model.dart';
import '../models/user_model.dart';
import '../models/banner_model.dart';
import '../models/coupon_model.dart';

class InitialSeedData {
  static List<ProductModel> get defaultProducts => [
        ProductModel(
          id: 'prod_1',
          name: 'Apple iPhone 16 Pro Max 256GB Natural Titanium',
          description: 'Designed with Grade 5 Titanium for superior strength and weight balance. Super Retina XDR display with ProMotion and A18 Pro chip.',
          price: 4699.00,
          originalPrice: 5099.00,
          discountPercent: 8.0,
          category: 'Electronics',
          subCategory: 'Smartphones',
          brand: 'Apple',
          stock: 45,
          rating: 4.9,
          reviewCount: 342,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80',
            'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        ProductModel(
          id: 'prod_2',
          name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones - Black',
          description: 'Industry-leading noise cancellation with two processors and 8 microphones. Up to 30 hours battery life with quick charging.',
          price: 1149.00,
          originalPrice: 1399.00,
          discountPercent: 18.0,
          category: 'Electronics',
          subCategory: 'Audio',
          brand: 'Sony',
          stock: 28,
          rating: 4.8,
          reviewCount: 189,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
        ),
        ProductModel(
          id: 'prod_3',
          name: 'Samsung Galaxy S25 Ultra 512GB Titanium Gray',
          description: 'Built-in S Pen, Snapdragon 8 Elite Processor, 200MP Quad Telephoto Camera system with 100x Space Zoom.',
          price: 5099.00,
          originalPrice: 5499.00,
          discountPercent: 7.0,
          category: 'Electronics',
          subCategory: 'Smartphones',
          brand: 'Samsung',
          stock: 19,
          rating: 4.7,
          reviewCount: 95,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        ProductModel(
          id: 'prod_4',
          name: 'Apple MacBook Air 15-inch M3 Chip 16GB RAM 512GB SSD Midnight',
          description: 'Incredibly thin and fast. M3 chip delivers powerful CPU and GPU performance with up to 18 hours of battery life.',
          price: 4999.00,
          originalPrice: 5399.00,
          discountPercent: 7.0,
          category: 'Electronics',
          subCategory: 'Laptops',
          brand: 'Apple',
          stock: 12,
          rating: 4.9,
          reviewCount: 210,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
        ),
        ProductModel(
          id: 'prod_5',
          name: 'Nike Air Max 270 Sneakers - Black / White',
          description: 'Boasts Nike biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.',
          price: 549.00,
          originalPrice: 699.00,
          discountPercent: 21.0,
          category: 'Fashion',
          subCategory: 'Shoes',
          brand: 'Nike',
          stock: 60,
          rating: 4.6,
          reviewCount: 144,
          isExpress: true,
          isFeatured: false,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
        ),
        ProductModel(
          id: 'prod_6',
          name: 'Dyson Airwrap Multi-Styler Complete Long - Strawberry Bronze',
          description: 'Curl, shape, smooth and hide flyaways with Coanda airflow mechanism. Engineered for multiple hair types.',
          price: 2199.00,
          originalPrice: 2499.00,
          discountPercent: 12.0,
          category: 'Beauty',
          subCategory: 'Hair Care',
          brand: 'Dyson',
          stock: 8,
          rating: 4.9,
          reviewCount: 520,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
        ),
        ProductModel(
          id: 'prod_7',
          name: 'PlayStation 5 Slim Digital Edition Consoles',
          description: 'Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do.',
          price: 1749.00,
          originalPrice: 1999.00,
          discountPercent: 13.0,
          category: 'Electronics',
          subCategory: 'Gaming',
          brand: 'Sony',
          stock: 35,
          rating: 4.9,
          reviewCount: 810,
          isExpress: true,
          isFeatured: true,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
        ),
        ProductModel(
          id: 'prod_8',
          name: 'Nespresso Vertuo Pop Coffee Machine - Spicy Red',
          description: 'Centrifusion extraction technology to gently and precisely brew coffee with delicious crema.',
          price: 599.00,
          originalPrice: 749.00,
          discountPercent: 20.0,
          category: 'Home',
          subCategory: 'Appliances',
          brand: 'Nespresso',
          stock: 14,
          rating: 4.7,
          reviewCount: 98,
          isExpress: false,
          isFeatured: false,
          isActive: true,
          images: [
            'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
          ],
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
        ),
      ];

  static List<CategoryModel> get defaultCategories => [
        CategoryModel(
          id: 'cat_1',
          name: 'Electronics',
          icon: '⚡️',
          bannerUrl: 'https://images.unsplash.com/photo-1498049860654-af1a5c57abf3?w=800&q=80',
          productCount: 1420,
          isFeatured: true,
          createdAt: DateTime.now(),
        ),
        CategoryModel(
          id: 'cat_2',
          name: 'Fashion',
          icon: '👗',
          bannerUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80',
          productCount: 3890,
          isFeatured: true,
          createdAt: DateTime.now(),
        ),
        CategoryModel(
          id: 'cat_3',
          name: 'Home',
          icon: '🏠',
          bannerUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80',
          productCount: 2150,
          isFeatured: true,
          createdAt: DateTime.now(),
        ),
        CategoryModel(
          id: 'cat_4',
          name: 'Beauty',
          icon: '💄',
          bannerUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
          productCount: 940,
          isFeatured: true,
          createdAt: DateTime.now(),
        ),
        CategoryModel(
          id: 'cat_5',
          name: 'Supermarket',
          icon: '🛒',
          bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
          productCount: 5400,
          isFeatured: true,
          createdAt: DateTime.now(),
        ),
        CategoryModel(
          id: 'cat_6',
          name: 'Baby & Kids',
          icon: '🍼',
          bannerUrl: '',
          productCount: 820,
          isFeatured: false,
          createdAt: DateTime.now(),
        ),
      ];

  static List<OrderModel> get defaultOrders => [
        OrderModel(
          id: 'ord_101',
          orderNumber: '#N-984210',
          customerId: 'usr_1',
          customerName: 'Mohammed Al-Mansoori',
          customerEmail: 'm.almansoori@gmail.com',
          customerPhone: '+971 50 849 2011',
          items: [
            OrderItemModel(
              productId: 'prod_1',
              productName: 'Apple iPhone 16 Pro Max 256GB Natural Titanium',
              productImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80',
              price: 4699.00,
              quantity: 1,
              variant: '256GB Titanium',
            ),
            OrderItemModel(
              productId: 'prod_2',
              productName: 'Sony WH-1000XM5 Wireless Headphones',
              productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
              price: 1149.00,
              quantity: 1,
            ),
          ],
          totalAmount: 5848.00,
          subtotal: 5848.00,
          shippingFee: 0.0,
          status: 'Pending',
          paymentMethod: 'Apple Pay',
          paymentStatus: 'Paid',
          deliveryAddress: 'Villa 45, Al Wasl Road, Jumeirah 2, Dubai, UAE',
          orderDate: DateTime.now().subtract(const Duration(minutes: 12)),
          updatedAt: DateTime.now().subtract(const Duration(minutes: 12)),
        ),
        OrderModel(
          id: 'ord_102',
          orderNumber: '#N-984209',
          customerId: 'usr_2',
          customerName: 'Sarah Jenkins',
          customerEmail: 'sarah.j@outlook.com',
          customerPhone: '+971 55 921 4480',
          items: [
            OrderItemModel(
              productId: 'prod_6',
              productName: 'Dyson Airwrap Multi-Styler Complete',
              productImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
              price: 2199.00,
              quantity: 1,
            ),
          ],
          totalAmount: 2199.00,
          subtotal: 2199.00,
          shippingFee: 0.0,
          status: 'Processing',
          paymentMethod: 'Credit Card',
          paymentStatus: 'Paid',
          deliveryAddress: 'Apartment 1402, Marina Gate 1, Dubai Marina, UAE',
          orderDate: DateTime.now().subtract(const Duration(hours: 2)),
          updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        OrderModel(
          id: 'ord_103',
          orderNumber: '#N-984208',
          customerId: 'usr_3',
          customerName: 'Tariq Al-Hashemi',
          customerEmail: 'tariq.h@yahoo.com',
          customerPhone: '+966 50 112 3344',
          items: [
            OrderItemModel(
              productId: 'prod_7',
              productName: 'PlayStation 5 Slim Digital Edition',
              productImage: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80',
              price: 1749.00,
              quantity: 1,
            ),
            OrderItemModel(
              productId: 'prod_5',
              productName: 'Nike Air Max 270 Sneakers',
              productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
              price: 549.00,
              quantity: 1,
              variant: 'Size EU 43',
            ),
          ],
          totalAmount: 2298.00,
          subtotal: 2298.00,
          shippingFee: 0.0,
          status: 'Shipped',
          paymentMethod: 'Noon Pay',
          paymentStatus: 'Paid',
          deliveryAddress: 'King Fahd Road, Olaya District, Riyadh, Saudi Arabia',
          orderDate: DateTime.now().subtract(const Duration(hours: 8)),
          updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
        ),
        OrderModel(
          id: 'ord_104',
          orderNumber: '#N-984207',
          customerId: 'usr_4',
          customerName: 'Fatima Zayed',
          customerEmail: 'fatima.zayed@gmail.com',
          customerPhone: '+971 52 334 5599',
          items: [
            OrderItemModel(
              productId: 'prod_3',
              productName: 'Samsung Galaxy S25 Ultra 512GB',
              productImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
              price: 5099.00,
              quantity: 1,
            ),
          ],
          totalAmount: 5099.00,
          subtotal: 5099.00,
          shippingFee: 0.0,
          status: 'Delivered',
          paymentMethod: 'Credit Card',
          paymentStatus: 'Paid',
          deliveryAddress: 'Corniche Road, Al Khalidiya, Abu Dhabi, UAE',
          orderDate: DateTime.now().subtract(const Duration(days: 1)),
          updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
        ),
      ];

  static List<BannerModel> get defaultBanners => [
        BannerModel(
          id: 'ban_1',
          title: 'YELLOW FRIDAY SALE - Up to 70% OFF',
          imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200&q=80',
          targetCategory: 'All',
          isActive: true,
          position: 1,
          createdAt: DateTime.now(),
        ),
        BannerModel(
          id: 'ban_2',
          title: 'Electronics Mega Deals - Noon Express ⚡️ Delivery',
          imageUrl: 'https://images.unsplash.com/photo-1498049860654-af1a5c57abf3?w=1200&q=80',
          targetCategory: 'Electronics',
          isActive: true,
          position: 2,
          createdAt: DateTime.now(),
        ),
        BannerModel(
          id: 'ban_3',
          title: 'Latest Fashion Trends & Brands',
          imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&q=80',
          targetCategory: 'Fashion',
          isActive: true,
          position: 3,
          createdAt: DateTime.now(),
        ),
      ];

  static List<UserModel> get defaultUsers => [
        UserModel(
          id: 'usr_1',
          name: 'Mohammed Al-Mansoori',
          email: 'm.almansoori@gmail.com',
          phone: '+971 50 849 2011',
          totalOrders: 14,
          totalSpent: 18450.00,
          isBlocked: false,
          joinDate: DateTime.now().subtract(const Duration(days: 120)),
        ),
        UserModel(
          id: 'usr_2',
          name: 'Sarah Jenkins',
          email: 'sarah.j@outlook.com',
          phone: '+971 55 921 4480',
          totalOrders: 8,
          totalSpent: 9200.00,
          isBlocked: false,
          joinDate: DateTime.now().subtract(const Duration(days: 90)),
        ),
        UserModel(
          id: 'usr_3',
          name: 'Tariq Al-Hashemi',
          email: 'tariq.h@yahoo.com',
          phone: '+966 50 112 3344',
          totalOrders: 22,
          totalSpent: 34100.00,
          isBlocked: false,
          joinDate: DateTime.now().subtract(const Duration(days: 200)),
        ),
        UserModel(
          id: 'usr_4',
          name: 'Fatima Zayed',
          email: 'fatima.zayed@gmail.com',
          phone: '+971 52 334 5599',
          totalOrders: 5,
          totalSpent: 6700.00,
          isBlocked: false,
          joinDate: DateTime.now().subtract(const Duration(days: 45)),
        ),
      ];

  static List<CouponModel> get defaultCoupons => [
        CouponModel(
          id: 'coup_1',
          code: 'NOON10',
          discountAmount: 10.0,
          isPercentage: true,
          minSpend: 100.0,
          usageLimit: 1000,
          usageCount: 412,
          isActive: true,
          expiryDate: DateTime.now().add(const Duration(days: 30)),
        ),
        CouponModel(
          id: 'coup_2',
          code: 'EXPRESS50',
          discountAmount: 50.0,
          isPercentage: false,
          minSpend: 300.0,
          usageLimit: 500,
          usageCount: 189,
          isActive: true,
          expiryDate: DateTime.now().add(const Duration(days: 15)),
        ),
        CouponModel(
          id: 'coup_3',
          code: 'WELCOME20',
          discountAmount: 20.0,
          isPercentage: true,
          minSpend: 150.0,
          usageLimit: 2000,
          usageCount: 890,
          isActive: true,
          expiryDate: DateTime.now().add(const Duration(days: 60)),
        ),
      ];
}
